package com.example.service;

import com.example.dto.KisanMitraChatRequest;
import com.example.dto.KisanMitraChatResponse;
import com.example.entity.UserQuery;
import com.example.repository.UserQueryRepository;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Service;
import org.springframework.web.client.RestClient;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;

@Service
public class KisanMitraService {

    private final WBCropKnowledgeBase knowledgeBase;
    private final WeatherService weatherService;
    private final RestClient restClient;
    private final ObjectMapper objectMapper;
    private final UserQueryRepository userQueryRepository;

    @Value("${kisanmitra.provider:gemini}")
    private String provider;

    @Value("${GEMINI_API_KEY:}")
    private String geminiApiKey;

    @Value("${GROQ_API_KEY:}")
    private String groqApiKey;

    @Value("${OPENROUTER_API_KEY:}")
    private String openRouterApiKey;

    @Value("${KISANMITRA_TIMEOUT_MS:12000}")
    private int timeoutMs;

    @Autowired
    public KisanMitraService(WBCropKnowledgeBase knowledgeBase,
                             WeatherService weatherService,
                             RestClient.Builder restClientBuilder,
                             ObjectMapper objectMapper,
                             UserQueryRepository userQueryRepository) {
        this.knowledgeBase = knowledgeBase;
        this.weatherService = weatherService;
        this.restClient = restClientBuilder
                .defaultHeader("User-Agent", "FasalSathi-KisanMitra/1.0")
                .build();
        this.objectMapper = objectMapper;
        this.userQueryRepository = userQueryRepository;
    }

    public KisanMitraService(WBCropKnowledgeBase knowledgeBase,
                             WeatherService weatherService,
                             RestClient.Builder restClientBuilder,
                             ObjectMapper objectMapper) {
        this(knowledgeBase, weatherService, restClientBuilder, objectMapper, null);
    }

    public KisanMitraChatResponse ask(KisanMitraChatRequest request) {
        return ask(request, "anonymous");
    }

    public KisanMitraChatResponse ask(KisanMitraChatRequest request, String username) {
        String question = request == null || request.question() == null ? "" : request.question().trim();
        String crop = request == null || request.crop() == null ? "" : request.crop().trim();
        String district = request == null || request.district() == null ? "" : request.district().trim();
        String language = request == null || request.language() == null || request.language().isBlank() ? "en" : request.language();

        if (question.isBlank()) {
                KisanMitraChatResponse response = new KisanMitraChatResponse(
                    "KisanMitra is offline, try again shortly.",
                    "The local KVK should be consulted for urgent crop decisions until the hosted chatbot is available.",
                    language,
                    false,
                    "offline"
            );
                    recordQuery(question, username, crop, district, language, response);
                    return response;
        }

        try {
            String answer = callHostedLlm(question, crop, district, language);
                    KisanMitraChatResponse response = new KisanMitraChatResponse(
                    answer,
                    "The answer was generated by the external hosted model and should still be checked with your local KVK before applying a treatment or chemical recommendation.",
                    language,
                    true,
                    resolveProviderName()
            );
                    recordQuery(question, username, crop, district, language, response);
                    return response;
        } catch (Exception exception) {
                    KisanMitraChatResponse response = new KisanMitraChatResponse(
                    "KisanMitra is offline, try again shortly.",
                    "The local KVK should be consulted for urgent crop decisions until the hosted chatbot is available.",
                    language,
                    false,
                    "offline"
            );
                    recordQuery(question, username, crop, district, language, response);
                    return response;
        }
    }

                private void recordQuery(String question, String username, String crop, String district,
                             String language, KisanMitraChatResponse response) {
                    if (userQueryRepository == null) {
                        return;
                    }
                userQueryRepository.save(new UserQuery(
                    question,
                    username == null || username.isBlank() ? "anonymous" : username,
                    crop,
                    district,
                    language,
                    response.grounded() ? "ANSWERED" : "OFFLINE",
                    response.source()
                ));
                }

    private String callHostedLlm(String question, String crop, String district, String language) throws Exception {
        String activeProvider = resolveProviderName();
        String context = buildContextPrompt(crop, district);
        String prompt = "You are KisanMitra, a multilingual agricultural assistant for Indian farmers. " +
                "Answer only from the farmer context and the local agronomy guidance provided below. " +
                "Never invent a pesticide product name, dosage, PHI, REI, or pest-control recommendation. " +
                "If the information is missing or uncertain, explicitly tell the farmer to check with their local KVK/agriculture office. " +
                "Use the farmer's language: " + language + ".\n\n" +
                "Farmer question: " + question + "\n\n" +
                context + "\n\n" +
                "Return a helpful, concise answer in plain language for a farmer. Keep it practical and safe.";

        return switch (activeProvider) {
            case "gemini" -> callGemini(prompt);
            case "groq" -> callGroq(prompt);
            case "openrouter" -> callOpenRouter(prompt);
            default -> throw new IllegalStateException("No supported hosted KisanMitra provider is configured.");
        };
    }

    private String buildContextPrompt(String crop, String district) {
        String districtContext = district != null && !district.isBlank() ? knowledgeBase.getDistrictContext(district) : "Unknown district; use general West Bengal agronomy and ask the farmer to confirm the district.";
        String cropContext = crop != null && !crop.isBlank() ? "Selected crop: " + crop + "." : "Crop not specified by the farmer.";
        String weatherContext = "Current context: " + districtContext + " " + cropContext;
        return weatherContext;
    }

    private String callGemini(String prompt) throws Exception {
        String apiKey = geminiApiKey;
        if (apiKey == null || apiKey.isBlank()) {
            throw new IllegalStateException("GEMINI_API_KEY is not configured.");
        }

        Map<String, Object> payload = new LinkedHashMap<>();
        Map<String, Object> content = new LinkedHashMap<>();
        content.put("parts", List.of(Map.of("text", prompt)));
        payload.put("contents", List.of(content));

        String rawResponse = restClient.post()
                .uri("https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=" + apiKey)
                .contentType(MediaType.APPLICATION_JSON)
                .body(payload)
                .retrieve()
                .body(String.class);

        JsonNode root = objectMapper.readTree(rawResponse);
        JsonNode text = root.path("candidates").path(0).path("content").path("parts").path(0).path("text");
        if (text.isMissingNode() || text.asText().isBlank()) {
            throw new IllegalStateException("Gemini returned no answer text.");
        }
        return text.asText();
    }

    private String callGroq(String prompt) throws Exception {
        String apiKey = groqApiKey;
        if (apiKey == null || apiKey.isBlank()) {
            throw new IllegalStateException("GROQ_API_KEY is not configured.");
        }

        Map<String, Object> payload = new LinkedHashMap<>();
        payload.put("model", "llama-3.1-8b-instant");
        payload.put("temperature", 0.2);
        payload.put("max_tokens", 500);
        payload.put("messages", List.of(
                Map.of("role", "system", "content", "You are KisanMitra, a safe agricultural assistant. Never invent pesticide dosage, product names, PHI, or REI."),
                Map.of("role", "user", "content", prompt)
        ));

        String rawResponse = restClient.post()
                .uri("https://api.groq.com/openai/v1/chat/completions")
                .contentType(MediaType.APPLICATION_JSON)
                .header("Authorization", "Bearer " + apiKey)
                .body(payload)
                .retrieve()
                .body(String.class);

        JsonNode root = objectMapper.readTree(rawResponse);
        JsonNode text = root.path("choices").path(0).path("message").path("content");
        if (text.isMissingNode() || text.asText().isBlank()) {
            throw new IllegalStateException("Groq returned no answer text.");
        }
        return text.asText();
    }

    private String callOpenRouter(String prompt) throws Exception {
        String apiKey = openRouterApiKey;
        if (apiKey == null || apiKey.isBlank()) {
            throw new IllegalStateException("OPENROUTER_API_KEY is not configured.");
        }

        Map<String, Object> payload = new LinkedHashMap<>();
        payload.put("model", "openai/gpt-4o-mini");
        payload.put("temperature", 0.2);
        payload.put("messages", List.of(
                Map.of("role", "system", "content", "You are KisanMitra, a safe agricultural assistant for Indian farmers. Never invent a pesticide dosage, product name, PHI, or REI. Refer to local KVK if the answer is uncertain."),
                Map.of("role", "user", "content", prompt)
        ));

        String rawResponse = restClient.post()
                .uri("https://openrouter.ai/api/v1/chat/completions")
                .contentType(MediaType.APPLICATION_JSON)
                .header("Authorization", "Bearer " + apiKey)
                .header("HTTP-Referer", "https://fasalsathi.local")
                .header("X-Title", "FasalSathi KisanMitra")
                .body(payload)
                .retrieve()
                .body(String.class);

        JsonNode root = objectMapper.readTree(rawResponse);
        JsonNode text = root.path("choices").path(0).path("message").path("content");
        if (text.isMissingNode() || text.asText().isBlank()) {
            throw new IllegalStateException("OpenRouter returned no answer text.");
        }
        return text.asText();
    }

    private String resolveProviderName() {
        if (provider != null && !provider.isBlank()) {
            String normalized = provider.trim().toLowerCase(Locale.ROOT);
            if (normalized.equals("groq") && groqApiKey != null && !groqApiKey.isBlank()) return "groq";
            if (normalized.equals("openrouter") && openRouterApiKey != null && !openRouterApiKey.isBlank()) return "openrouter";
            if (normalized.equals("gemini") && geminiApiKey != null && !geminiApiKey.isBlank()) return "gemini";
        }

        if (geminiApiKey != null && !geminiApiKey.isBlank()) return "gemini";
        if (groqApiKey != null && !groqApiKey.isBlank()) return "groq";
        if (openRouterApiKey != null && !openRouterApiKey.isBlank()) return "openrouter";
        return "gemini";
    }
}
